---
#######################################################################
# Kubernetes Deployment for Wazuh Kibana container
#######################################################################
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: wazuh-kibana
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-kibana
  template:
    metadata:
      labels:
        app: wazuh-kibana
      name: wazuh-kibana
    spec:
      containers:
        - name: wazuh-kibana
          image: 'wazuh/wazuh-kibana:3.2.0_6.2.1'
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
          ports:
            - containerPort: 5601
              name: kibana
          command:
            - /wait-for-it.sh
            - elasticsearch
          env:
            - name: NODE_OPTIONS
              value: '--max-old-space-size=3072'
---